# # Name of your workflow
# name: Build Workflow

# # Define the trigger event(s)
# # on: pull_request
# on: [push]

# # Jobs run in parallel by default, each runs steps in sequence
# jobs:

#     checkout-our-repo:
#         runs-on: ubuntu-latest
#         steps:
#             # Use github.com/actions/checkout to check out this repo
#             - name: Check out this repo
#               uses: actions/checkout@v3

#     compile-firmware:
#         needs: checkout-our-repo
#         runs-on: ubuntu-latest
#         steps:
#           - name: Build STM32CubeIde project
#             uses: xanderhendriks/action-build-stm32cubeide@v10.0
#             with:
#               project-path: 'DAQ_System'
#               project-target: 'DAQ_System/Debug'

#     run-unit-tests:
#         needs: checkout-our-repo
#         runs-on: ubuntu-latest
#         steps:
#             - name: Run Google Test
#               run: |
#                   cd DAQ_System/Tests
#                   python3 run_tests.py
            









# Name of your workflow
name: Build Workflow

# Define the trigger event(s)
# on: pull_request
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:

    compile-firmware:
        runs-on: ubuntu-latest
        steps:
        
            # Use github.com/actions/checkout to check out this repo
          - name: Check out this repo
            uses: actions/checkout@v3
          
          - name: Build STM32CubeIde project
            uses: xanderhendriks/action-build-stm32cubeide@v10.0
            with:
              project-path: 'DAQ_System'
              project-target: 'DAQ_System/Debug'
    
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:

            # Use github.com/actions/checkout to check out this repo
            - name: Check out this repo
              uses: actions/checkout@v3

            - name: Run Google Test
              run: |
                  cd DAQ_System/Tests
                  python3 run_tests.py
            