name: CI Build

# Define the trigger event(s)
on: [push, pull_request]

# Jobs run in parallel by default, each runs steps in sequence
jobs:

    compile-firmware:
        runs-on: ubuntu-latest
        steps:
        
          - name: Check out this repo
            uses: actions/checkout@v3
          
          - name: Build stm32CubeIDE project
            uses: xanderhendriks/action-build-stm32cubeide@v10.0
            with:
              project-path: 'DAQ_System'
              project-target: 'DAQ_System/Debug'
    
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:

            - name: Check out this repo
              uses: actions/checkout@v3

            - name: Install Ninja
              run: sudo apt-get install ninja-build

            - name: Build and run unit tests
              run: |
                  cd DAQ_System/Tests
                  cmake -G "Ninja" -S . -B ./build
                  cd build
                  ninja
                  ./daq-unit-tests
            