name: CI Build

# Define the trigger event(s)
on: push

# Jobs run in parallel by default, each runs steps in sequence
jobs:

    compile-firmware:
        runs-on: ubuntu-latest
        steps:
        
          - name: Check out this repo
            uses: actions/checkout@v3
            with:
              submodules: 'true'
          
          - name: Build stm32CubeIDE project
            uses: xanderhendriks/action-build-stm32cubeide@v10.0
            with:
              project-path: 'Project/DAQ_System'
              project-target: 'DAQ_System/Debug'
            